# Generated by Django 4.2.15 on 2025-11-09 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='hash',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='hospital_code',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ts',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='curr_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
