# Generated by Django 4.2.15 on 2025-11-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_alter_department_code_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_staffprofile_per_user'),
        ),
    ]
