# Generated by Django 4.2.15 on 2025-11-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staffprofile_unique_staffprofile_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='staff', to='core.role'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.department'),
        ),
    ]
